### ISSUE TITLE
jQuery 3 support?

### ISSUE THREAD

**Issue by Silex** [flowplayer/flowplayer#1208]
Hello,

Is jQuery 3 support planned soon?

```
jQuery.Deferred exception: Cannot read property 'split' of undefined TypeError: Cannot read property 'split' of undefined
    at r (https://releases.flowplayer.org/6.0.5/commercial/flowplayer.min.js:7:6876)
    at t.exports.e.sourcesFromVideoTag (https://releases.flowplayer.org/6.0.5/commercial/flowplayer.min.js:7:7243)
    at E (https://releases.flowplayer.org/6.0.5/commercial/flowplayer.min.js:7:30365)
    at HTMLDivElement.<anonymous> (https://releases.flowplayer.org/6.0.5/commercial/flowplayer.min.js:7:30602)
    at Function.each (https://127.0.0.1/assets/jquery/jquery.self-06c43429d1047ce3f355da574d8a9750209971b8b1b8f264f91f5518c5fcc060.js?body=1:363:19)
    at jQuery.fn.init.each (https://127.0.0.1/assets/jquery/jquery.self-06c43429d1047ce3f355da574d8a9750209971b8b1b8f264f91f5518c5fcc060.js?body=1:158:17)
    at jQuery.fn.init.x.fn.flowplayer (https://releases.flowplayer.org/6.0.5/commercial/flowplayer.min.js:7:30447)
    at HTMLDocument.<anonymous> (https://releases.flowplayer.org/6.0.5/commercial/flowplayer.min.js:7:29908)
    at mightThrow (https://127.0.0.1/assets/jquery/jquery.self-06c43429d1047ce3f355da574d8a9750209971b8b1b8f264f91f5518c5fcc060.js?body=1:3584:29)
    at process (https://127.0.0.1/assets/jquery/jquery.self-06c43429d1047ce3f355da574d8a9750209971b8b1b8f264f91f5518c5fcc060.js?body=1:3652:12) undefined
```

Same error with flowplayer `7.0.4`.

**Comment by Silex** [comment]
@nnarhinen: any news?

**Comment by blacktrash** [comment]
@Silex - could you be more specific as to your setup - i.e. *minimal* sample page?
A quick stab seems to work fine: http://flowplayer.blacktrash.org/fp7/minimal.html

**Comment by Silex** [comment]
Sorry, it looks like I messed up because I cannot reproduce the problem anymore :confused: 

I'll reopen if I this happen again, it was probably a cache issue when I upgraded jQuery on my end.
